### ISSUE TITLE
MATLAB/Octave support

### ISSUE THREAD

**Issue by krishnakumarg1984** [jbyuki/dash.nvim#1]
Very nice plugin. I notice that there is an unpopulated MATLAB entry  in your READM.me table of languages. Do you plan to support MATLAB/Octave?

**Comment by jbyuki** [comment]
Thanks, I appreciate that. 
I remember adding this entry because I needed it for a project but in the end, I did it in Python and forgot to remove it in the README. I'm not sure if it's even possible because if I recall correctly, Matlab doesn't provide a CLI execution environment. Any further infos on that subject would be welcome.
